apiVersion: v1 
kind: Pod
metadata:
  name: printenv
spec:
  containers:
  - name: printenv
    image: hookenz/printenv
    ports:
    - containerPort: 8080
    env:
    - name: GREETING
      value: "Warm greetings to"
    - name: HONORIFIC
      value: "The Most Honorable"
    - name: NAME
      value: "Kubernetes"
