---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: printenv
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: printenv
  replicas: 1 
  template: 
    metadata:
      labels:
        app: printenv
    spec:
      containers:
      - name: printenv
        image: hookenz/printenv
        ports:
        - containerPort: 8080
        env:
        - name: FOO
          value: BART
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: printenv
  type: LoadBalancer
