apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: printenv-demo-container
    image: hookenz/printenv
  restartPolicy: OnFailure
